### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by bladeoflight16** [thomasgalliker/EnumUtils#5]
Searchable HTML documentation is needed to avoid having to dig through source (or generated definitions in VS).

**Comment by thomasgalliker** [comment]
To be honest, I'm not a big fan of generated documentations. They contain mostly boilerplate text (like comments on properties: "Gets or sets the name", etc...). Which tool would you prefer? DocFx? Doxygen?
I think we could also create a wikipage or a better readme.md (with an API overview or something?). 

When I explore a new library, I usually use the ObjectBrowser (VS) or AssemblyExplorer (Resharper) to get an overview. These tools also show xml documentation (if it exists).
